# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .virtualmachine import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "azure-quickstart-compute",
  "mod": "index",
  "fqn": "pulumi_azure_quickstart_compute",
  "classes": {
   "azure-quickstart-compute:index:virtualmachine": "Virtualmachine"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "azure-quickstart-compute",
  "token": "pulumi:providers:azure-quickstart-compute",
  "fqn": "pulumi_azure_quickstart_compute",
  "class": "Provider"
 }
]
"""
)
